# --- API Key Configuration ---
# --- Konfiguracja Klucza API ---
KEY: "*****" # <-- Wklej tutaj swój prawdziwy klucz / Paste your real key here

# --- Main Project Configuration ---
# --- Główna Konfiguracja Projektu ---
# The main, absolute path to the project directory. All other paths will be built based on this one.
# Główna, absolutna ścieżka do katalogu projektu. Wszystkie inne ścieżki będą budowane na jej podstawie.
base_path: "/home/luke_blue_lox/PycharmProjects/BLOX-TAK-GEMINI"

# --- RAG Pipeline Configuration (Updated for 2-DB Architecture) ---
# --- Konfiguracja Potoku RAG (Zaktualizowana dla Architektury 2 Baz) ---
rag_pipeline_config:
  # Source folders for the two types of corpora
  # Foldery źródłowe dla dwóch typów korpusów
  legal_source_folder: "TEMP/LAW"
  case_source_folder: "TEMP/CASE_DOCS"

  # Vector Database folders for each corpus
  # Foldery baz wektorowych dla każdego korpusu
  vector_db_legal_folder: "KNOWLEDGE_BASE/VECTOR_DB_LEGAL"
  vector_db_case_folder: "KNOWLEDGE_BASE/VECTOR_DB_CASE"

  # Folder for log files generated by the RAG scripts
  # Folder na pliki logów generowane przez skrypty RAG
  log_folder: "LOGS"

  # Model used for creating vector embeddings
  # Model używany do tworzenia wektorów (embeddings)
  embedding_model: "models/text-embedding-004"

  # Large Language Model used for generating answers
  # Duży Model Językowy używany do generowania odpowiedzi
  llm_model: "gemini-1.5-flash"

# --- Configuration for the Content Merging Script ---
# --- Konfiguracja dla Skryptu Łączącego Treści ---
merger_script_config:
  source_folder: "TEMP"
  output_folder: "FOR_ANALYSIS"
  font_path: "UbuntuMono-Regular.ttf"
  font_name: "UbuntuMono"
  font_size: 12
  model_name: "gemini-1.5-flash"
  ocr_prompt: "GEMINI, Make OCR. Do not add any additional information, just the text."
  audio_prompt: "Transcribe the audio recording. Correct the text for grammar and style, returning only the final, clean text in Polish."
  ocr_resolution: 150

# --- Configuration for the Translation Script ---
# --- Konfiguracja dla Skryptu Tłumaczącego ---
translator_script_config:
  source_folder: "FOR_ANALYSIS"
  output_folder: "TRANSLATIONS"
  font_path: "UbuntuMono-Regular.ttf"
  font_name: "UbuntuMono"
  font_size: 12
  model_name: "gemini-1.5-flash"
  chunk_size_chars: 30000

  # List of target languages for translation
  # Lista języków docelowych dla tłumaczenia
  target_languages:
    - "English"
    - "Polish"
    #- "Arabic"
    #- "Chinese"
    #- "Czech"
    #- "French"
    #- "German"
    #- "Hebrew"
    #- "Japanese"
    #- "Persian"
    #- "Russian"
    #- "Spanish"
    #- "Ukrainian"

# --- Configuration for Other Scripts (e.g., Google Drive Upload) ---
# --- Konfiguracja dla Innych Skryptów (np. Przesyłanie na Dysk Google) ---
folders_to_check:
  #- image_output
  #- TRANSLATIONS
  #- audio_input
  #- FOR_ANALYSIS
  #- LOGS
  #- audio_logs
  #- image_input
  #- PROCESSED_OUTPUT
  #- audio_output
  #- image_logs
  #- TEMP
  #- KNOWLEDGE_BASE

# Parent folder ID on Google Drive, used by the upload script
# ID folderu nadrzędnego na Dysku Google, używane przez skrypt do przesyłania plików
google_drive_parent_folder_id: "*****"